name: ouija-board
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.24
  - requests>=2.31
  - pip
  - pip:
      - python-dotenv>=1.0.0
      - openai>=1.6.0
      - pyserial>=3.5

